### ISSUE TITLE
Is there a plan to support play 2.8.0

### ISSUE THREAD

**Issue by footballer1993** [pac4j/play-pac4j#269]
I tried, but get an error:
error] D:\Projekte\EstimationControl\conf\routes:130:1: type CallbackController is not a member of package org.pac4j.play
[error] GET         /callback                   @org.pac4j.play.CallbackController.callback()

**Comment by leleuj** [comment]
Yes, we will support Play 2.8.0, but I'm not sure when. Are you sure your error is related to Play v2.8.0? It seems strange...

**Comment by thirdteeth** [comment]
we have an issue when using this with Play Java v2.8.0, since Play Java delete the deprecated API of play.mvc.Http.Context and related API, when we create org.pac4j.play.PlayWebContext object, it throws a ClassNotFoundException

**Comment by jeffwji** [comment]
After upgraded from 2.7 to 2.8. I got this exception: 

com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: play/mvc/Http$Context 

I think it might due to the same problem.

**Comment by leleuj** [comment]
Certainly

**Comment by rania-globalorange** [comment]
I took a look into how the deprecated Http.Context could be replaced and it looks like there is a lot of impact. Without replacing this it's not possible to move to play 2.8. @leleuj do you have a plan of approach? I could possibly help

**Comment by leleuj** [comment]
Not yet. I plan to resume my work on play-pac4j next week with in order:
create version 9, update to pac4j v4, fix bugs, add Scala 2.13
then
create v10, update to Play 2.8.x, remove Scala 2.11...

**Comment by SoerenSilkjaer** [comment]
I made a pr that upgrades this project to pac4j v4 #267
Hope it helps in the upgrade process.

**Comment by leleuj** [comment]
play-pac4j v9 which is based on Play 2.7 and pac4j v4 has been cleaned from the deprecated `Http.context` class: it should work for Play 2.8. Can you give it a try? Thanks

**Comment by SoerenSilkjaer** [comment]
> play-pac4j v9 which is based on Play 2.7 and pac4j v4 has been cleaned from the deprecated `Http.context` class: it should work for Play 2.8. Can you give it a try? Thanks

I am seeing AnonymousProfile in my list of profiles. The comment say that pac4j tries to omit this profile from the list, and it has in previous versions. Is the AnonymousProfile there on purpose now?

**Comment by leleuj** [comment]
The code has been moved to `ProfileHelper.flatIntoOneProfile` on which the `ProfileManager.get` relies.
The `AnonymousProfile` should be there if it's the only profile. Otherwise, it will be omitted.

**Comment by SoerenSilkjaer** [comment]
> The code has been moved to `ProfileHelper.flatIntoOneProfile` on which the `ProfileManager.get` relies.
> The `AnonymousProfile` should be there if it's the only profile. Otherwise, it will be omitted.
Aha. In my application, it is the only profile, when the other clients i configured cannot resolve to a profile, is this what you mean with the only profile? Or do you mean that is has to be the only Client aswell?

**Comment by leleuj** [comment]
Yes, one profile, not one client. There was a reason behind that, but I can't remember it.

You can override the `ProfileManager` with a new one and set it via `Config.defaultProfileManagerFactory`. I don't think this is a good idea though. You should certainly find another way.

**Comment by pankajsonawane4** [comment]
is play-pac4j v9 is available? I cannot see it in releases.

**Comment by leleuj** [comment]
Not yet. I plan the release at the end of this week or at the beginning of next week.

Currently, you need to add the Sonatype snapshots repository to get the play-pac4j v9.0.0-RC3-SNAPSHOT.

**Comment by leleuj** [comment]
play-pac4j v9 for Play 2.7 and play-pac4j v10 for Play 2.8 have been released.
