### ISSUE TITLE
SecurityFilter not work in play 2.6.2 

### ISSUE THREAD

**Issue by schmielinski** [pac4j/play-pac4j#186]
I'm using 4.0.0-SNAPSHOT version but with
**play.filters.enabled+=org.pac4j.play.filters.SecurityFilter** or **play.http.filters = "filters.Filters**
I'm getting:
Error injecting constructor, java.lang.NoSuchMethodError: play.api.mvc.EssentialFilter.$init$(Lplay/api/mvc/EssentialFilter;)V
  at org.pac4j.play.filters.SecurityFilter.<init>(SecurityFilter.scala:67)
  at org.pac4j.play.filters.SecurityFilter.class(SecurityFilter.scala:67)
  while locating org.pac4j.play.filters.SecurityFilter
  at play.api.http.EnabledFilters.<init>(HttpFilters.scala:68)
  at play.utils.Reflect$.bindingsFromConfiguration(Reflect.scala:58):
Binding(class play.api.http.EnabledFilters to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)

**Comment by taggiasco** [comment]
Hi @schmielinski ,

I tried to add the filter with 
`play.filters.enabled+=org.pac4j.play.filters.SecurityFilter`
and the application has started correctly.

It seems you encounter an injection error because a method does not exist. Are you sure that Play 2.6.2 is used ?

**Comment by schmielinski** [comment]
Hi @taggiasco,

Thank you for your answer. I checked again my build.sbt file and it turned out that I have not changed the scala version for 2.12.x. Now everything works. Thanks!
