### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by huhonator** [pac4j/play-pac4j#49]
I was using this version of play-pac4j 

"org.pac4j" % "play-pac4j_java" % "1.1.1",
      "org.pac4j" % "pac4j-http" % "1.4.2-SNAPSHOT",
      "org.pac4j" % "pac4j-cas" % "1.4.2-SNAPSHOT",
      "org.pac4j" % "pac4j-oauth" % "1.4.2-SNAPSHOT"

on project one year ago. Now I got back, checked out the repo and getting this error during the build:

`sbt.PlayExceptions$CompilationException: Compilation error[Cannot use a method returning play.libs.F.Promise[play.mvc.Result] as an Handler]
	at sbt.PlayReloader$$anon$2$$anonfun$reload$2$$anonfun$apply$15$$anonfun$apply$16.apply(PlayReloader.scala:349) ~[na:na]
	at sbt.PlayReloader$$anon$2$$anonfun$reload$2$$anonfun$apply$15$$anonfun$apply$16.apply(PlayReloader.scala:349) ~[na:na]
	at scala.Option.map(Option.scala:133) ~[scala-library.jar:na]
	at sbt.PlayReloader$$anon$2$$anonfun$reload$2$$anonfun$apply$15.apply(PlayReloader.scala:349) ~[na:na]
	at sbt.PlayReloader$$anon$2$$anonfun$reload$2$$anonfun$apply$15.apply(PlayReloader.scala:346) ~[na:na]
	at scala.Option.map(Option.scala:133) ~[scala-library.jar:na]
[warn] play - No application found at invoker init`

**Comment by leleuj** [comment]
v1.1.1 is an old one which works with the v1.4.1 of pac4j. Replace the 1.4.2-SNAPSHOT (which is the next development iteration and may be different) with the 1.4.1.

**Comment by huhonator** [comment]
at first, thank you for your response. Now I am getting this:

` [info] Compiling 50 Scala sources and 121 Java sources to .../target/scala-2.10/classes...
[warn] .../conf/routes:25: unreachable code
[warn] POST        /callback                                      org.pac4j.play.CallbackController.callback()
[warn] there were 2 feature warnings; re-run with -feature for details
[warn] two warnings found
[error] Error: Could not find or load main class @.tmp.sbt_82ae252f.argfile
[error] (compile:compile) javac returned nonzero exit code
[error] application - 

! @6l6djn5kk - Internal server error, for (GET) [/] ->

sbt.PlayExceptions$UnexpectedException: Unexpected exception[Compilation failed without reporting any problem!?]
	at sbt.PlayReloader$$anon$2$$anonfun$reload$2$$anonfun$apply$15$$anonfun$apply$17.apply(PlayReloader.scala:350) ~[na:na]
	at sbt.PlayReloader$$anon$2$$anonfun$reload$2$$anonfun$apply$15$$anonfun$apply$17.apply(PlayReloader.scala:350) ~[na:na]
	at scala.Option.getOrElse(Option.scala:108) ~[scala-library.jar:na]
	at sbt.PlayReloader$$anon$2$$anonfun$reload$2$$anonfun$apply$15.apply(PlayReloader.scala:349) ~[na:na]
	at sbt.PlayReloader$$anon$2$$anonfun$reload$2$$anonfun$apply$15.apply(PlayReloader.scala:346) ~[na:na]
	at scala.Option.map(Option.scala:133) ~[scala-library.jar:na]
Caused by: sbt.compiler.CompileFailed: null
	at sbt.compiler.JavaCompiler$$anon$1.compile(JavaCompiler.scala:59) ~[na:na]
	at sbt.compiler.JavaTool$class.apply(JavaCompiler.scala:26) ~[na:na]
	at sbt.compiler.JavaCompiler$$anon$1.apply(JavaCompiler.scala:51) ~[na:na]
	at sbt.compiler.JavaCompiler$class.compile(JavaCompiler.scala:17) ~[na:na]
	at sbt.compiler.JavaCompiler$$anon$1.compile(JavaCompiler.scala:51) ~[na:na]
	at sbt.compiler.AggressiveCompile$$anonfun$4$$anonfun$compileJava$1$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(AggressiveCompile.scala:83) ~[na:na]
[warn] play - No application found at invoker init
 `

**Comment by leleuj** [comment]
Are you trying to build pac4j or your own application?

**Comment by huhonator** [comment]
my own, using pac4j as a dependency

**Comment by huhonator** [comment]
any other advice @leleuj ?

**Comment by leleuj** [comment]
I've never encountered this error. Very strange! Does it work without ```pac4j``` ?

**Comment by leleuj** [comment]
One more thing: what version of Play do you use?

**Comment by huhonator** [comment]
2.1.1

**Comment by leleuj** [comment]
Indeed, for Play 2.1.x, you need to use the ```play-pac4j_java``` version 1.1.x.

Can you try to upgrade to the last one: ```play-pac4j``` v1.1.4 and ```pac4j``` v1.6?

**Comment by huhonator** [comment]
I tried it before, but I think something must changed in that version, because I am getting another error. Wait a sec, i will paste an error stack with new versions of dependency

**Comment by huhonator** [comment]
[warn] .../conf/routes:25: unreachable code
[warn] POST        /callback                                      org.pac4j.play.CallbackController.callback()
[warn] there were 2 feature warnings; re-run with -feature for details
[warn] two warnings found
[error] Error: Could not find or load main class @.tmp.sbt_e2225c06.argfile
[error] (compile:compile) javac returned nonzero exit code
[error] application - 

! @6lchog7ml - Internal server error, for (GET) [/] ->

sbt.PlayExceptions$UnexpectedException: Unexpected exception[Compilation failed without reporting any problem!?]
	at sbt.PlayReloader$$anon$2$$anonfun$reload$2$$anonfun$apply$15$$anonfun$apply$17.apply(PlayReloader.scala:350) ~[na:na]
	at sbt.PlayReloader$$anon$2$$anonfun$reload$2$$anonfun$apply$15$$anonfun$apply$17.apply(PlayReloader.scala:350) ~[na:na]
	at scala.Option.getOrElse(Option.scala:108) ~[scala-library.jar:na]
	at sbt.PlayReloader$$anon$2$$anonfun$reload$2$$anonfun$apply$15.apply(PlayReloader.scala:349) ~[na:na]
	at sbt.PlayReloader$$anon$2$$anonfun$reload$2$$anonfun$apply$15.apply(PlayReloader.scala:346) ~[na:na]
	at scala.Option.map(Option.scala:133) ~[scala-library.jar:na]
Caused by: sbt.compiler.CompileFailed: null
	at sbt.compiler.JavaCompiler$$anon$1.compile(JavaCompiler.scala:59) ~[na:na]
	at sbt.compiler.JavaTool$class.apply(JavaCompiler.scala:26) ~[na:na]
	at sbt.compiler.JavaCompiler$$anon$1.apply(JavaCompiler.scala:51) ~[na:na]
	at sbt.compiler.JavaCompiler$class.compile(JavaCompiler.scala:17) ~[na:na]
	at sbt.compiler.JavaCompiler$$anon$1.compile(JavaCompiler.scala:51) ~[na:na]
